openapi: 3.0.3
info:
  title: 'Talkdesk Challenge API'
  version: '1.0'
  contact:
    name: 'Mikayel Aghasyan'
    email: 'mikayel.aghasyan@gmail.com'
servers:
  - url: 'http://localhost:9000/api'
    description: 'Local Server'
  - url: '{scheme}://{host}/api'
    description: 'Custom Server'
    variables:
      scheme:
        enum:
          - http
          - https
        default: http
      host:
        default: 'localhost:9000'
paths:
  /calls:
    post:
      tags:
        - Calls
      operationId: 'AddCall'
      description: 'Adds a single call'
      requestBody:
        $ref: '#/components/requestBodies/AddCall'
      responses:
        201:
          $ref: '#/components/responses/AddCallResponse'
        400:
          description: 'Request is not valid'
    get:
      tags:
        - Calls
      operationId: 'GetCalls'
      description: 'Gets calls'
      parameters:
        - $ref: '#/components/parameters/CallType'
        - $ref: '#/components/parameters/PageNumber'
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/SortField'
        - $ref: '#/components/parameters/SortDirection'
      responses:
        200:
          $ref: '#/components/responses/CallsPageResponse'
  /calls/{id}:
    delete:
      tags:
        - Calls
      operationId: 'RemoveCall'
      description: 'Removes a call'
      parameters:
        - $ref: '#/components/parameters/CallId'
      responses:
        204:
          description: 'Call successfully removed'
        400:
          description: 'Call id is not provided'
        404:
          description: 'Call with id not found'
  /calls/bulk:
    post:
      tags:
        - Calls
      operationId: 'AddCalls'
      description: 'Adds multiple calls'
      requestBody:
        $ref: '#/components/requestBodies/AddCalls'
      responses:
        201:
          $ref: '#/components/responses/AddCallsResponse'
        400:
          description: 'Request is not valid'
  /stats:
    get:
      tags:
        - Stats
      operationId: 'GetStats'
      description: 'Get call statistics'
      responses:
        200:
          $ref: '#/components/responses/StatsResponse'
components:
  schemas:
    Id:
      format: uuid
      type: string
    CallType:
      type: string
      enum:
        - INBOUND
        - OUTBOUND
    Phone:
      type: string
      pattern: '^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\s./0-9]*$'
    Cost:
      type: number
      format: double
    Duration:
      description: 'Duration in seconds'
      type: integer
    CallProperties:
      type: object
      required:
        - callerNumber
        - calleeNumber
        - start
        - end
        - type
      x-dependencies:
        - relation: greater
          properties:
            - end
            - start
          data-format: date-time
        - relation: not-equal
          properties:
            - callerNumber
            - calleeNumber
      properties:
        callerNumber:
          $ref: '#/components/schemas/Phone'
        calleeNumber:
          $ref: '#/components/schemas/Phone'
        start:
          format: date-time
          type: string
        end:
          format: date-time
          type: string
        type:
          $ref: '#/components/schemas/CallType'
    Call:
      allOf:
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/Id'
        - $ref: '#/components/schemas/CallProperties'
        - type: object
          properties:
            cost:
              $ref: '#/components/schemas/Cost'
    NumberOfCallsByPhone:
      type: object
      properties:
        phone:
          $ref: '#/components/schemas/Phone'
        numberOfCalls:
          type: integer
    Stat:
      type: object
      properties:
        date:
          format: date
          type: string
        totalDurationByCallType:
          type: object
          properties:
            INBOUND:
              $ref: '#/components/schemas/Duration'
            OUTBOUND:
              $ref: '#/components/schemas/Duration'
        totalNumberOfCalls:
          type: integer
        numberOfCallsByCaller:
          type: array
          items:
            $ref: '#/components/schemas/NumberOfCallsByPhone'
        numberOfCallsByCallee:
          type: array
          items:
            $ref: '#/components/schemas/NumberOfCallsByPhone'
        totalCost:
          $ref: '#/components/schemas/Cost'
  securitySchemes: {}
  requestBodies:
    AddCall:
      description: 'Add call'
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CallProperties'
          example:
            callerNumber: "+37455000000"
            calleeNumber: "+37455111111"
            start: "2021-01-25T12:00:00Z"
            end: "2021-01-25T12:15:00Z"
            type: "OUTBOUND"
    AddCalls:
      description: 'Add multiple calls'
      required: true
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/CallProperties'
          example:
            - callerNumber: "+37455000000"
              calleeNumber: "+37455111111"
              start: "2021-01-25T12:00:00Z"
              end: "2021-01-25T12:15:00Z"
              type: "OUTBOUND"
            - callerNumber: "+37455222222"
              calleeNumber: "+37455000000"
              start: "2021-01-26T15:00:00Z"
              end: "2021-01-26T15:05:00Z"
              type: "INBOUND"
  responses:
    AddCallResponse:
      description: 'Call successfully added'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Call'
          example:
            id: "00000000-0000-0000-0000-000000000000"
            callerNumber: "+37455000000"
            calleeNumber: "+37455111111"
            start: "2021-01-25T12:00:00Z"
            end: "2021-01-25T12:15:00Z"
            type: "OUTBOUND"
            cost: 1.0
    AddCallsResponse:
      description: 'Calls successfully added'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Call'
          example:
            - id: "00000000-0000-0000-0000-000000000000"
              callerNumber: "+37455000000"
              calleeNumber: "+37455111111"
              start: "2021-01-25T12:00:00Z"
              end: "2021-01-25T12:15:00Z"
              type: "OUTBOUND"
              cost: 1.0
            - id: "00000000-0000-0000-0000-000000000000"
              callerNumber: "+37455222222"
              calleeNumber: "+37455000000"
              start: "2021-01-26T15:00:00Z"
              end: "2021-01-26T15:05:00Z"
              type: "INBOUND"
              cost: 0.0
    CallsPageResponse:
      description: 'Calls page'
      content:
        application/json:
          schema:
            type: object
            properties:
              pageNumber:
                type: integer
              pageSize:
                type: integer
              totalCount:
                type: integer
                format: int64
              items:
                type: array
                items:
                  $ref: '#/components/schemas/Call'
          example:
            pageNumber: 0
            pageSize: 10
            totalCount: 2
            items:
              - id: "00000000-0000-0000-0000-000000000000"
                callerNumber: "+37455000000"
                calleeNumber: "+37455111111"
                start: "2021-01-25T12:00:00Z"
                end: "2021-01-25T12:15:00Z"
                type: "OUTBOUND"
                cost: 1.0
              - id: "00000000-0000-0000-0000-000000000000"
                callerNumber: "+37455222222"
                calleeNumber: "+37455000000"
                start: "2021-01-26T15:00:00Z"
                end: "2021-01-26T15:05:00Z"
                type: "INBOUND"
                cost: 0.0
    StatsResponse:
      description: 'Calls statistics'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Stat'
          example:
            - date: "2021-01-25"
              totalDurationByCallType:
                INBOUND: 0
                OUTBOUND: 900
              totalNumberOfCalls: 1
              numberOfCallsByCaller:
                - phone: "+37455000000"
                  numberOfCalls: 1
              numberOfCallsByCallee:
                - phone: "+37455111111"
                  numberOfCalls: 1
              totalCost: 1.0
            - date: "2021-01-26"
              totalDurationByCallType:
                INBOUND: 300
                OUTBOUND: 0
              totalNumberOfCalls: 1
              numberOfCallsByCaller:
                - phone: "+37455222222"
                  numberOfCalls: 1
              numberOfCallsByCallee:
                - phone: "+37455000000"
                  numberOfCalls: 1
              totalCost: 0.0
  parameters:
    CallId:
      in: path
      description: Call Id
      name: id
      required: true
      schema:
        $ref: '#/components/schemas/Id'
    CallType:
      in: query
      description: Call type
      name: type
      required: false
      schema:
        type: string
        enum:
          - INBOUND
          - OUTBOUND
    PageNumber:
      in: query
      description: Page number
      name: page_num
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0
    PageSize:
      in: query
      description: Page size
      name: page_size
      required: false
      schema:
        type: integer
        minimum: 1
        default: 10
    SortField:
      in: query
      description: Sort field
      name: sort_by
      required: false
      schema:
        type: string
        enum:
          - callerNumber
          - calleeNumber
          - start
          - end
          - type
    SortDirection:
      in: query
      description: Sort direction
      name: sort_dir
      required: false
      schema:
        type: string
        enum:
          - ASC
          - DESC
        default: ASC
tags:
  - name: Calls
    description: Call management
  - name: Stats
    description: Call statistics
security: []
